DROP TABLE IF EXISTS CITY;

CREATE TABLE CITY (CITY_ID INT PRIMARY KEY AUTO_INCREMENT, CITY_CODE VARCHAR, NAME VARCHAR, COUNTRY VARCHAR, POPULATION INT, INSERTDATE DATE);
-- CREATE TABLE CITY (CITY_ID  INT, CITY_CODE VARCHAR , NAME VARCHAR, COUNTRY VARCHAR, POPULATION INT , PRIMARY KEY(CITY_ID, CITY_CODE));

INSERT INTO CITY (CITY_ID, CITY_CODE, NAME, COUNTRY, POPULATION, INSERTDATE) VALUES (1, '001','San Francisco', 'US', 10000, CURRENT_TIMESTAMP());
INSERT INTO CITY (CITY_ID, CITY_CODE, NAME, COUNTRY, POPULATION, INSERTDATE) VALUES (2, '002','서울', 'KR', 20000, CURRENT_DATE());
INSERT INTO CITY (CITY_ID, CITY_CODE, NAME, COUNTRY, POPULATION, INSERTDATE) VALUES (3, '003','東京', 'JP', 30000, CURRENT_DATE());
INSERT INTO CITY (CITY_ID, CITY_CODE, NAME, COUNTRY, POPULATION, INSERTDATE) VALUES (4, '004','부산', 'KR', 40000, CURRENT_DATE());

CREATE TABLE PERSON (ID INT PRIMARY KEY AUTO_INCREMENT, FIRST_NAME VARCHAR, LAST_NAME VARCHAR, CITY_ID INT);

INSERT INTO PERSON (FIRST_NAME, LAST_NAME, CITY_ID) VALUES ('son', 'seungwoo', 1);