DROP TABLE IF EXISTS CITY;

CREATE TABLE CITY (CITY_ID INT PRIMARY KEY AUTO_INCREMENT, CITY_CODE VARCHAR, NAME VARCHAR, COUNTRY VARCHAR, POPULATION INT);
-- CREATE TABLE CITY (CITY_ID  INT, CITY_CODE VARCHAR , NAME VARCHAR, COUNTRY VARCHAR, POPULATION INT , PRIMARY KEY(CITY_ID, CITY_CODE));

INSERT INTO CITY (CITY_ID, CITY_CODE, NAME, COUNTRY, POPULATION) VALUES (1, '001','San Francisco', 'US', 10000);
INSERT INTO CITY (CITY_ID, CITY_CODE, NAME, COUNTRY, POPULATION) VALUES (2, '002','서울', 'KR', 20000);
INSERT INTO CITY (CITY_ID, CITY_CODE, NAME, COUNTRY, POPULATION) VALUES (3, '003','東京', 'JP', 30000);
INSERT INTO CITY (CITY_ID, CITY_CODE, NAME, COUNTRY, POPULATION) VALUES (4, '004','부산', 'KR', 40000);